// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ididkfewmabvfethvuol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkaWRrZmV3bWFidmZldGh2dW9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDY4NTksImV4cCI6MjA2NjYyMjg1OX0.ZR-nb3LeoTgbN3xFihfMzyA1S-2EKYwBy18OdoYJjPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);